server {
    listen 80;
    server_name localhost;
    root /var/www/public;
    index index.php;

    # Disable symlink protection
    disable_symlinks off;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /storage {
        alias /var/www/storage/app/public;
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}